### ISSUE TITLE
Possibility to add custom httpGetter

### ISSUE THREAD

**Issue by The-Redhat** [eGust/flutter_cache_store#1]
Hey it would be nice if you can add a custom httpGetter, like available in flutter_cache_manager.

**Comment by eGust** [comment]
Just check their new option. Sure it's doable. I'd like to make it more flexible. Maybe I will find some time next week to code.

**Comment by The-Redhat** [comment]
Ok thanks!

**Comment by eGust** [comment]
Added custom `fetch` and the new version had been published.
Let me know if you find any issue.
Thanks.
