### ISSUE TITLE
APP重启后出错

### ISSUE THREAD

**Issue by lmanliang** [eGust/flutter_cache_store#11]
貌似找不到档案

![image](https://user-images.githubusercontent.com/6987926/71924630-50625d80-31ca-11ea-9ef2-9bde2d5b2da3.png)

操作顺序
1. 正常启动程序 -> 第一次启用 ok
2. 关闭程序，重启，未能正常运作，出现以上错误
3. 不是所有的cache 都失效，仅有部份失效

**Comment by eGust** [comment]
没能重现你出现的问题，但是重新实现了一下清理文件的逻辑。如果还是出错的话，能用下面的代码做模板复现一下么？
https://gist.github.com/eGust/b49acc3bbbc954d209182082c2ed7dd2

**Comment by lmanliang** [comment]
经查，可能的原因是
1. 我将cache store 封存在我的function里
2. 首页开启，会同时执行二次，但不同的function 对像
所以产生这个问题

现行将二个function另行独立，暂时未发生

James <notifications@github.com> 於 2020年1月11日 週六 下午3:19寫道：
