### ISSUE TITLE
How do you define custom duration for different requests?

### ISSUE THREAD

**Issue by brettpappas** [eGust/flutter_cache_store#15]
I want to fetch data from an API with multiple endpoints. I want to cache some requests for 60 seconds while caching other requests for 12 hours without relying on the cache-control headers sent back from the server response. 

Is this possible with this plugin? It would be nice if there was a way to pass the TTL along with the `getFile()` request as an additional parameter.

**Comment by eGust** [comment]
probably can have 2 instances with different namespace and policy settings, but not sure if it suits your requirement.
