### ISSUE TITLE
StateError (Bad state: Insecure HTTP is not allowed by platform: http://xxx.xxx.xx.xx:3333/api/test)

### ISSUE THREAD

**Issue by Shiba-Kar** [eGust/flutter_cache_store#19]
flutter 2.0

**Comment by eGust** [comment]
Is your PR #20 to address this issue? Did not have time to look at 2.0 yet

**Comment by Shiba-Kar** [comment]
``` android:usesCleartextTraffic="true" ``` need to be added in <Application tag
