### ISSUE TITLE
Custom fetch not passed to Utils.download

### ISSUE THREAD

**Issue by rhulka** [eGust/flutter_cache_store#2]
Hello @eGust,

Thank you for this package.

I think I found an issue https://github.com/eGust/flutter_cache_store/blob/master/lib/src/cache_store.dart#L141 fetch parameter not passed to Utils.download so it always uses default because of fetch == null. I tried to cache JSON-RPC responses (POST) and it cost me a few hours of debugging :)

**Comment by eGust** [comment]
Hi @rhulka , yes you are right. Thank you for reporting. I will fix it soon

**Comment by eGust** [comment]
Hi @rhulka , would like to try if it's been fixed? The new version has been published.

btw, i also added optional `fetch` param to `getFile`. hopefully you will find it more convenient.

**Comment by eGust** [comment]
should be fixed
