### ISSUE TITLE
this library can be integrated with Chopper library?

### ISSUE THREAD

**Issue by pishguy** [eGust/flutter_cache_store#4]
i have a question about caching `http` responses which we use [chopper](https://github.com/lejard-h/chopper) library,

can we this feature in your library?

**Comment by eGust** [comment]
According to that library, it works for all the platforms. But mine is only for Flutter.

This library is based on files, while a RESTful library apparently must be based on requests. So the simple answer is NO.

Apart from that, it's not a good idea to cache API on the request layer.
